### ISSUE TITLE
    from scrapy.spider import CrawlSpider, Rule ImportError: No module named spider

### ISSUE THREAD

**Issue by esbarila** [luisramirez-m/mercadolibre-scrapy#6]
`(terrenalia) stiva@stiva-MS-7972 ~/Escritorio/virtualenvs/terrenalia/terrenalia $ scrapy crawl terrenalia -t csv
Traceback (most recent call last):
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/crawler.py", line 251, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/crawler.py", line 338, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stiva/Escritorio/virtualenvs/terrenalia/terrenalia/terrenalia/spiders/spider.py", line 6, in <module>
    from scrapy.spider import CrawlSpider, Rule
ImportError: No module named spider
`

A partir del proyecto de mercado hice mi propio scrapper "terrenalia", pero me sale éste error y no se como resolverlo.

**Comment by Santiago-Rocha** [comment]
Creo que el modulo se llama 'scrapy.spiders', con 's' al final
